stages:
  - build
  - deploy
  - push 
build:
  build:
  image: docker:19.03.12
  stage: build
  # services:
  #   - docker:19.03.12-dind
  # script:
  #   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  #   - docker build -t $CI_REGISTRY/group/project/image:latest .
  #   - docker push $CI_REGISTRY/group/project/image:latest
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:

    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "docker/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
   - echo $KUBE_CONFIG | base64 -d  > /tmp/kube_config.yaml 
   - export KUBECONFIG=/tmp/kube_config.yaml 
   - kubectl apply -f appset.yaml -n argocd   

   #- kubectl get pods 
push:
  image: docker:19.03.12
  stage: push
  services:
    - docker:19.03.12-dind
  script:
    - cd docker
    - docker login registry.gitlab.com -u abhi1-rithu2 -p jyothi3113
    - docker build -t registry.gitlab.com/abhi1-rithu2/first:latest .
    - docker push registry.gitlab.com/abhi1-rithu2/first:latest
