apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-sample'
    spec:
      destination:
        namespace: default
        server: '{{url}}'
      project: default
      source:
        path: helm
        repoURL: https://oauth2:glpat-rCaj67Dy6kStxUgZe_y_@gitlab.com/abhi1-rithu2/first.git
        targetRevision: main
      syncPolicy:
         automated:
           prune: true
           selfHeal: true
         syncOptions:
        - CreateNamespace=true
